### ISSUE TITLE
Ability to specify channel folder name

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#4] opened 2020-05-10 03:04 UTC
For the moment, the folder name is simply the channel name. This can be an issue if: 
- there are two channels with the same name 
- the uploader changes their channel name

As an alternative, give the user the ability to choose the destination folder name

e.g. `python yt-backup.py add_channel --channel_id <id> --folder-name "Custom Name [Details]"`

**Comment by Zulux91** [comment] 2020-05-10 03:46
> give the user the ability to choose the destination folder name

That option is already available in your config file.  To avoid both the issues you're describing you can also add the channel id to the folder name. Two channels might have the same name but never the same channel id.

**Comment by sideloading** [comment] 2020-05-10 04:50
@Zulux91 are you referring to the `"naming-format":` inside the config file?

I tried to specify the folder name using `%(uploader)s [%(channel_id)s]/(upload_date)s %(title).100s %(height)sp %(id)s.%(ext)s`, and the yt-backup would create the folder output inside the temp directory, but in the destination directory it is just the Channel Name.

I'd also get the following error:
`2020-05-10 02:53:06,529 - yt-backup - ERROR - Cannot find any downloaded file. Please check youtube-dl output by hand...`

Removing `%(uploader)s [%(channel_id)s]/` from the config has no issues moving files over.

**Comment by oneandonlyjason** [comment] 2020-05-10 12:56
> I'd also get the following error:
2020-05-10 02:53:06,529 - yt-backup - ERROR - Cannot find any downloaded file. Please check youtube-dl output by hand...

I already reported that Problem Yesterday and he is working on a fix for it

**Comment by sideloading** [comment] 2020-05-10 13:58
The destination folder is hard-coded as the channel name currently
https://github.com/w0d4/yt-backup/blob/master/yt-backup.py#L702

**Comment by Zulux91** [comment] 2020-05-10 20:00
Again @bpo5r5 , there's no hardcoded option. Update to the last version of this script and inspect your config.json: `naming-format": "%(uploader)s.%(upload_date)s.%(title)s.%(resolution)s.%(id)s.%(ext)s` is th default config. I for instance I'm using this `%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s` . Just edit anything to suit your needs, as easy as that.

Note that this `%(uploader)s [%(channel_id)s]/` is going to create an extra dir and the script doesn't have (yet) the ability to look for such changes.

**Comment by sideloading** [comment] 2020-05-11 00:52
@Zulux91 This issue is regarding the Directory name, not the *File name*. I understand I can specify the naming scheme for files, but the destination folder where the files are stored is hard-coded as mentioned previously (Line 702). 

...`--output " + config["base"]["download_dir"] + "/\"" + channel_name + "\"/\"" + config["youtube-dl"]["naming-format"]`...

**Comment by w0d4** [comment] 2020-05-11 07:11
Hi, I understand the problem. I will try to parse the target file name from youtube-dl output. So everyone can choose a folder structure under channel_name as everyone wants.
I think I don't want to get away from channel_name and then naming format.
But, if you add a deeper folder structure under channel_name, it will break. So I accept this as a bug, since all folder structures under a channels name should be possible. This relates to @Zulux91 statement: Note that this %(uploader)s [%(channel_id)s]/ is going to create an extra dir and the script doesn't have (yet) the ability to look for such changes.

**Comment by sideloading** [comment] 2020-05-11 07:36
If you wish to keep the `channel_name` + [naming format], why not add an extra flag (as mentioned in the original issue description), where the user can specify that folder name? Maybe it could be added to the database to keep reference of the user assigned name.

**Comment by w0d4** [comment] 2020-05-11 07:42
I will add a feature to rename channel names.
I think the channel name comming from youtube is good in the first place. But I also accept that a user wants to change a channel name to something else. Also this would be reflected in download path naming.

**Comment by w0d4** [comment] 2020-05-11 08:19
I have added the feature with commit 564c4454324bd0f98614e4dcc750b48b3b58b693
Please test it if it's the thing you want.

**Comment by sideloading** [comment] 2020-05-11 09:25
So I've had a test, added the channel using `$ python yt-backup.py add_channel --channel_id <id> --username 'Channel Name [channel id]'`, which adds the channel fine in the DB. But when it comes to moving the file after downloading I get the message:
`2020-05-11 09:14:36,917 - yt-backup - ERROR - Cannot find any downloaded file. Please check youtube-dl output by hand...`.

I believe this is an issue with escaping the `[` `]` for rclone 😐  https://forum.rclone.org/t/which-special-characters-do-i-need-to-escape-why-cant-rclone-handle-it/3471

**Comment by w0d4** [comment] 2020-05-11 09:34
OK, thanks for the note with []. I don't assume a rclone problem here, since the rror is thrown here https://github.com/w0d4/yt-backup/blob/master/yt-backup.py#L779

I will try to reproduce this.

**Comment by w0d4** [comment] 2020-05-11 10:45
I released b11c577f2b94a102b5d2e66f8cee9f27b4181873
This should solve most of the issues with channel naming and subfolder sctructures on downloading.
Even your "naming-format": "%(uploader)s [%(channel_id)s]/%(upload_date)s %(title).100s %(height)sp %(id)s.%(ext)s" could work now

**Comment by sideloading** [comment] 2020-05-11 11:04
@w0d4 Great, that fixed it! Thanks so much for your quick fixes, really appreciated.

**Comment by w0d4** [comment] 2020-05-11 11:07
Maybe this lead to a new issue, if you hit a video which cannot be merged to mkv. If you find something like this, let me know about. I don't have a video at hand which cannot be converted to mp4.

**Comment by oneandonlyjason** [comment] 2020-05-11 11:27
Hey,
I found the problem you were talking about. I have a file here that was saved as mp4 and is not uploaded. But I don't get an error message either. He just skips the upload for this file.

**Comment by w0d4** [comment] 2020-05-11 11:39
Should also be fixed now. I found also one and implemented a fix for the problem. Try latest version. And report back. If not working I would appreciate the video ID.

**Comment by oneandonlyjason** [comment] 2020-05-11 11:41
Im using Commit 86c91ba from 21 minutes ago so im using the newest i think.
Here is the Error from the newest Version `Traceback (most recent call last):
  File "yt-backup.py", line 1083, in <module>
    download_videos()
  File "yt-backup.py", line 674, in download_videos
    video.runtime = get_video_duration(video_file)
  File "yt-backup.py", line 812, in get_video_duration
    return float(result.stdout)
ValueError: could not convert string to float: b'"My Path and the Video Name": No such file or directory\n'
`
I will send you the Video ID on reddit in a the chat window

**Comment by w0d4** [comment] 2020-05-11 12:07
Should be fixed in 123588f88ffca68aca7c70320c6a8b1061f7006d

**Comment by oneandonlyjason** [comment] 2020-05-11 12:08
Yes its working now thx!

**Closed as completed** 2020-05-11 12:09 UTC
Labels: bug

**Comment by sideloading** [comment] 2020-05-11 13:39
@w0d4 Just a quick question, is there any particular reason you choose to sanitize spaces with underscores? Same with `--restrict-filenames` on YTDL. If the files/directories are quoted, should I not have to worry?

**Comment by w0d4** [comment] 2020-05-11 15:50
Yes, in theory you are right. There is strong need to replace spaces. But since I have ssen to much things gone terribly wrong because of some totally not expected characters, I'm better safe than sorry in this case.
Just think of filenames including quotes... And some files you never expected would be moved to rclone remote.
If the user specifies them in the naming-format, the user is forced to escape the quotes. But when they come from youtube, I have to handle all special chars which could pssibly do something wrong.
If you want, I can move --restrict-filenames to the options in config file. So every user can choose to keep or drop the option on his own risk.
